echo Creating database tpch...
createdb tpch
echo Creating fixeddecimal extension...
psql tpch -c "create extension fixeddecimal;"
echo Building TPC-H schema...
psql tpch -f tpch-create_fixeddecimal.sql
echo Loading TPC-H data...
time python load3tb.py
echo Performing Vacuum freeze...
time psql tpch -c "vacuum freeze verbose;"
echo Creating indexes...
time python index_david_v8.py
echo Building foreign key constraints...
time python foreign_keys.py
echo Applying NDISTINCT fix...
psql tpch -f ndistinct-fix-3tb.sql
echo Performing ANALYZE of tpch database...
time psql tpch -c "analyze;"
echo Done.

