#!/bin/bash

# Configuration variables
# Scale factor. 1 = 1GB, 10 = 10GB. TPC-H has rules about which scale factors
# are considered valid for comparative purposes.
SCALE=10 #GB

# Other configuration variables
BASEDIR=$(dirname "$0")
BASEDIR=$(cd "$BASEDIR"; pwd)
#TPCHTMP=/dev/shm/$USER/tpch_tmp
#PGDATADIR=/dev/shm/$USER/pgdata${SCALE}GB
TPCHTMP=/AXLE/$USER/tpch_tmp
PGDATADIR=/AXLE/$USER/pgdata${SCALE}GB
PGPORT=5442
REMAKE_DATA=true
DB_NAME="tpch"
POPULATE_DB=true
CREATE_MIN_INDEXES=false
CREATE_ALL_INDEXES=true
PERFDATADIR=perfdata
CORES=`grep -c ^processor /proc/cpuinfo`
PGUSER="nobody"

# Install teardown() function to kill any lingering jobs
teardown() {
  echo "Cleaning up before exiting"
  sudo -u $PGUSER pg_ctl stop -m fast -D "$PGDATADIR" 2>/dev/null && sleep 1
  JOBS=$(jobs -p)
  test -z "$JOBS" || { kill $JOBS && sleep 2; }
  JOBS=$(jobs -p)
  test -z "$JOBS" || kill -9 $JOBS
}
test -z "${DEBUG-}" && trap "teardown" EXIT

# Set up perf
perf_set_kernel_params() {
  if [ -r /proc/sys/kernel/kptr_restrict ] && [ $(cat /proc/sys/kernel/kptr_restrict) -ne 0 ]; then
    echo "Perf requires reading kernel symbols."
    echo 0 | sudo tee /proc/sys/kernel/kptr_restrict
  fi
  if [ -r /proc/sys/kernel/perf_event_paranoid ] && [ $(cat /proc/sys/kernel/perf_event_paranoid) -ne -1 ]; then
    echo "Need to enable the reading of performance events."
    echo -1 | sudo tee /proc/sys/kernel/perf_event_paranoid
  fi
  if [ -r /proc/sys/kernel/perf_event_mlock_kb ] && [ $(cat /proc/sys/kernel/perf_event_mlock_kb) -lt 1024 ]; then
    echo "Need to give more memory to perf."
    echo 1024 | sudo tee /proc/sys/kernel/perf_event_mlock_kb
  fi
}

# Restart and drop caches
restart_drop_caches() {
    echo "Restart postgres and drop caches."
    sudo -u $PGUSER pg_ctl stop -D $PGDATADIR
    sync && echo 3 | sudo tee /proc/sys/vm/drop_caches
    sudo -u $PGUSER taskset -c 2 postgres -D "$PGDATADIR" -p $PGPORT &
    PGPID=$!
    while ! sudo -u $PGUSER pg_ctl status -D $PGDATADIR | grep "server is running" -q; do
        echo "Waiting for the Postgres server to start"
        sleep 3
    done
}

# Check for the running Postgres; exit if there is any on the given port
PGPORT_PROCLIST="$(lsof -i tcp:$PGPORT | tail -n +2 | awk '{print $2}')"
if [[ $(echo "$PGPORT_PROCLIST" | wc -w) -gt 0 ]];
then
  echo "The following processes have taken port $PGPORT"
  echo "Please terminate them before running this script"
  echo
  for p in $PGPORT_PROCLIST;
  do
    ps -o pid,cmd $p
  done
  exit -1
fi

# Check if a Postgres server is running in the same directory
if sudo -u $PGUSER pg_ctl status -D $PGDATADIR | grep "server is running" -q; then
  echo "A Postgres server is already running in the selected directory. Exiting."
  sudo -u $PGUSER pg_ctl status -D $PGDATADIR
  exit -2
fi

cd "$BASEDIR"
