#!/bin/bash

BASEDIR=$(dirname "$0")
BASEDIR=$(cd "$BASEDIR"; pwd)
. "$BASEDIR/pgtpch_defaults"

if [ $# -gt 0 ]; then
  PERFDATADIR="$PERFDATADIR-$1"
fi

if [ -r /proc/sys/kernel/kptr_restrict ] && [ $(cat /proc/sys/kernel/kptr_restrict) -ne 0 ]; then
  echo "Perf requires reading kernel symbols. Please enter your sudo password to allow this:"
  echo 0 | sudo tee /proc/sys/kernel/kptr_restrict
fi

for i in $(seq 1 22);
do
  ii=$(printf "%02d" $i)
  dir="$PERFDATADIR/q${ii}"
  mkdir -p $dir
  cd "$dir"
  perf record -g postgres -D $PGDATADIR -p $PGPORT &
  PGPID=$!
  while ! pg_ctl status -D $PGDATADIR | grep "server is running" -q; do
    echo "Waiting for the Postgres server to start"
    sleep 1
  done
  f="queries/q$ii.sql"
  echo "Running query: $i"
  /usr/bin/time -f '%e\n%Uuser %Ssystem %Eelapsed %PCPU (%Xtext+%Ddata %Mmax)k'\
    -o query_exec_seconds.txt \
    psql -p $PGPORT tpch <"$BASEDIR/$f"
  pg_ctl stop -D $PGDATADIR
  cgf="../q${ii}-callgraph.pdf"
  echo "Creating the call graph: $cgf"
  perf script | python "$BASEDIR/gprof2dot.py" -f perf | dot -Tpdf -o $cgf &
  cd - >/dev/null
done

for p in $(jobs -p);
do
  wait $p
done

