#!/bin/bash

speeds="1.40Ghz 1.90Ghz 2.30Ghz 2.80Ghz 3.10Ghz"
for speed in $speeds
do
	echo "****************** Setting CPU speeds to $speed *****************"
	for cpu in {0..7}
	do
		sudo cpufreq-set -c $cpu -f $speed 
		#echo $cpu $speed
	done
	echo "****************** Run the TPCH benchmark	*******************"
	./tpch_runone $1
	echo "****************** House Keeping ******************"
	mv perfdata-1GB perfdata-1GB-$speed
done

